# Cross-Sectional Stock Return Prediction

This notebook runs the attention experiment from `run_project_mhattn.py`.
This fixed-seed notebook is kept with outputs for reproducible single-seed comparison.

In [1]:
import importlib
import random
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from IPython import get_ipython

ip = get_ipython()
if ip is not None:
    ip.run_line_magic("matplotlib", "inline")
    try:
        from matplotlib_inline.backend_inline import set_matplotlib_formats
        set_matplotlib_formats("png")
    except Exception:
        pass

project_root = Path.cwd().resolve()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import stock_return_core as srp
import run_project_mhattn as mh

srp = importlib.reload(srp)
mh = importlib.reload(mh)
print(srp.__file__)
print(mh.__file__)

/home/hlc/ECE_C147A_Project/stock_return_project4.py
/home/hlc/ECE_C147A_Project/run_project_mhattn.py

In [2]:
# Quick run defaults for the seeded attention experiment.
START_DATE = "2015-01-01"
END_DATE = "2025-01-01"
LOOKBACK = 60
HORIZON = 5
UNIVERSE = "small"  # small | sp500 | nasdaq100 | auto
MODELS = ["RNN", "LSTM", "GRU", "TRANSFORMER"]
ATTN_HEADS = 4
DEVICE = mh.resolve_device()
SEED = 42

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        if hasattr(torch.backends, "cudnn"):
            torch.backends.cudnn.benchmark = False
            torch.backends.cudnn.deterministic = True

UNIVERSE_TO_TICKERS = {
    "small": srp.DEFAULT_LIQUID_TICKERS,
    "sp500": srp.SP500_TICKERS,
    "nasdaq100": srp.NASDAQ100_TICKERS,
    "auto": None,
}
TICKERS = UNIVERSE_TO_TICKERS[UNIVERSE]
print(f"Universe: {UNIVERSE}")
print(f"Seed: {SEED}")

# Universe filter: keep stocks that cover nearly the full sample window.
START_BUFFER_DAYS = 5
END_BUFFER_DAYS = 5
MIN_COVERAGE_RATIO = 0.95

Universe: small
Seed: 42

In [3]:
raw_prices = srp.download_price_history(start=START_DATE, end=END_DATE, tickers=TICKERS)

flat_prices = srp.flatten_price_frame(raw_prices).dropna(subset=["Close"]).copy()
all_dates = pd.Index(sorted(pd.to_datetime(flat_prices["Date"].unique())))
date_to_pos = {date: idx for idx, date in enumerate(all_dates)}

coverage = (
    flat_prices.groupby("Ticker")
    .agg(
        first_date=("Date", "min"),
        last_date=("Date", "max"),
        n_dates=("Date", "nunique"),
    )
    .reset_index()
)
coverage["first_pos"] = pd.to_datetime(coverage["first_date"]).map(date_to_pos)
coverage["last_pos"] = pd.to_datetime(coverage["last_date"]).map(date_to_pos)
coverage["coverage_ratio"] = coverage["n_dates"] / len(all_dates)

eligible_tickers = coverage.loc[
    (coverage["first_pos"] <= START_BUFFER_DAYS)
    & (coverage["last_pos"] >= len(all_dates) - 1 - END_BUFFER_DAYS)
    & (coverage["coverage_ratio"] >= MIN_COVERAGE_RATIO),
    "Ticker",
].tolist()

filtered_prices = raw_prices.loc[
    :,
    raw_prices.columns.get_level_values(0).isin(eligible_tickers),
]

print(
    f"Kept {len(eligible_tickers)} / {coverage.shape[0]} tickers "
    f"with >= {MIN_COVERAGE_RATIO:.0%} coverage and near-full sample history."
)
print(
    "Dropped examples:",
    coverage.loc[~coverage["Ticker"].isin(eligible_tickers), "Ticker"].head(10).tolist(),
)

experiment_data = srp.prepare_experiment_data(
    filtered_prices,
    horizon=HORIZON,
    lookback=LOOKBACK,
    train_size=0.7,
    val_size=0.15,
)
for split_name, split_df in experiment_data.splits.items():
    print(split_name, split_df["Date"].min(), split_df["Date"].max(), len(split_df))

Kept 49 / 50 tickers with >= 95% coverage and near-full sample history.
Dropped examples: ['UBER']

train 2015-02-02 00:00:00 2021-12-31 00:00:00 85407
val 2022-01-03 00:00:00 2023-06-29 00:00:00 18326
test 2023-06-30 00:00:00 2024-12-23 00:00:00 18326

In [4]:
MODEL_CONFIGS = {
    "RNN": srp.TrainConfig(
        batch_size=128,
        hidden_dim=64,
        num_layers=1,
        dropout=0.0,
        learning_rate=1e-4,
        weight_decay=1e-5,
        max_epochs=20,
        patience=6,
        grad_clip=1.0,
        device=DEVICE,
    ),
    "LSTM": srp.TrainConfig(
        batch_size=128,
        hidden_dim=64,
        num_layers=2,
        dropout=0.15,
        learning_rate=3e-4,
        weight_decay=1e-5,
        max_epochs=25,
        patience=6,
        grad_clip=1.0,
        device=DEVICE,
    ),
    "GRU": srp.TrainConfig(
        batch_size=128,
        hidden_dim=64,
        num_layers=2,
        dropout=0.15,
        learning_rate=1e-4,
        weight_decay=1e-5,
        max_epochs=25,
        patience=6,
        grad_clip=1.0,
        device=DEVICE,
    ),
    "TRANSFORMER": srp.TrainConfig(
        batch_size=256,
        hidden_dim=160,
        num_layers=3,
        dropout=0.15,
        num_heads=8,
        learning_rate=3e-4,
        weight_decay=5e-5,
        max_epochs=35,
        patience=10,
        grad_clip=1.0,
        device=DEVICE,
    ),
}
input_dim = len(experiment_data.feature_columns)
results = {}
for model_name in MODELS:
    train_config = MODEL_CONFIGS[model_name]
    set_seed(SEED)
    print(f"=== Notebook model: {model_name} (seed={SEED}) ===")
    if model_name == "RNN":
        model = srp.build_model(
            model_name="RNN",
            input_dim=input_dim,
            hidden_dim=train_config.hidden_dim,
            num_layers=train_config.num_layers,
            dropout=train_config.dropout,
        )
    elif model_name in {"LSTM", "GRU"}:
        model = mh.AttentionSequenceRegressor(
            input_dim=input_dim,
            hidden_dim=train_config.hidden_dim,
            num_layers=train_config.num_layers,
            dropout=train_config.dropout,
            cell_type=model_name,
            num_attn_heads=ATTN_HEADS,
        )
    elif model_name == "TRANSFORMER":
        model = srp.build_model(
            model_name="TRANSFORMER",
            input_dim=input_dim,
            hidden_dim=train_config.hidden_dim,
            num_layers=train_config.num_layers,
            dropout=train_config.dropout,
            num_heads=train_config.num_heads,
        )
    else:
        raise ValueError(f"Unsupported model: {model_name}")
    results[model_name] = mh.run_experiment(
        model,
        model_name,
        experiment_data,
        train_config,
    )

=== Notebook model: RNN (seed=42) ===

=== Training RNN ===

[train] batch 1/645 - loss: 0.247352

[train] batch 200/645 - loss: 0.021102

[train] batch 400/645 - loss: 0.011883

[train] batch 600/645 - loss: 0.008643

[train] batch 645/645 - loss: 0.008189

[val] batch 1/121 - loss: 0.002724

[val] batch 121/121 - loss: 0.002667

Epoch 1/20 - train_loss: 0.008189, val_loss: 0.002667, time: 5.8s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.002387

[train] batch 200/645 - loss: 0.001908

[train] batch 400/645 - loss: 0.001832

[train] batch 600/645 - loss: 0.001782

[train] batch 645/645 - loss: 0.001782

[val] batch 1/121 - loss: 0.002065

[val] batch 121/121 - loss: 0.002322

Epoch 2/20 - train_loss: 0.001782, val_loss: 0.002322, time: 5.0s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001476

[train] batch 200/645 - loss: 0.001633

[train] batch 400/645 - loss: 0.001634

[train] batch 600/645 - loss: 0.001614

[train] batch 645/645 - loss: 0.001619

[val] batch 1/121 - loss: 0.002153

[val] batch 121/121 - loss: 0.002244

Epoch 3/20 - train_loss: 0.001619, val_loss: 0.002244, time: 5.5s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001158

[train] batch 200/645 - loss: 0.001590

[train] batch 400/645 - loss: 0.001543

[train] batch 600/645 - loss: 0.001557

[train] batch 645/645 - loss: 0.001565

[val] batch 1/121 - loss: 0.002135

[val] batch 121/121 - loss: 0.002213

Epoch 4/20 - train_loss: 0.001565, val_loss: 0.002213, time: 5.6s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001555

[train] batch 200/645 - loss: 0.001576

[train] batch 400/645 - loss: 0.001541

[train] batch 600/645 - loss: 0.001544

[train] batch 645/645 - loss: 0.001542

[val] batch 1/121 - loss: 0.002231

[val] batch 121/121 - loss: 0.002225

Epoch 5/20 - train_loss: 0.001542, val_loss: 0.002225, time: 5.2s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.000777

[train] batch 200/645 - loss: 0.001573

[train] batch 400/645 - loss: 0.001557

[train] batch 600/645 - loss: 0.001532

[train] batch 645/645 - loss: 0.001525

[val] batch 1/121 - loss: 0.002096

[val] batch 121/121 - loss: 0.002190

Epoch 6/20 - train_loss: 0.001525, val_loss: 0.002190, time: 5.0s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001579

[train] batch 200/645 - loss: 0.001462

[train] batch 400/645 - loss: 0.001501

[train] batch 600/645 - loss: 0.001512

[train] batch 645/645 - loss: 0.001516

[val] batch 1/121 - loss: 0.002056

[val] batch 121/121 - loss: 0.002178

Epoch 7/20 - train_loss: 0.001516, val_loss: 0.002178, time: 5.1s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001530

[train] batch 200/645 - loss: 0.001498

[train] batch 400/645 - loss: 0.001497

[train] batch 600/645 - loss: 0.001511

[train] batch 645/645 - loss: 0.001507

[val] batch 1/121 - loss: 0.001995

[val] batch 121/121 - loss: 0.002177

Epoch 8/20 - train_loss: 0.001507, val_loss: 0.002177, time: 5.2s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001374

[train] batch 200/645 - loss: 0.001516

[train] batch 400/645 - loss: 0.001524

[train] batch 600/645 - loss: 0.001513

[train] batch 645/645 - loss: 0.001508

[val] batch 1/121 - loss: 0.002163

[val] batch 121/121 - loss: 0.002173

Epoch 9/20 - train_loss: 0.001508, val_loss: 0.002173, time: 5.0s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001472

[train] batch 200/645 - loss: 0.001490

[train] batch 400/645 - loss: 0.001491

[train] batch 600/645 - loss: 0.001501

[train] batch 645/645 - loss: 0.001506

[val] batch 1/121 - loss: 0.002128

[val] batch 121/121 - loss: 0.002186

Epoch 10/20 - train_loss: 0.001506, val_loss: 0.002186, time: 5.1s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.001506

[train] batch 200/645 - loss: 0.001511

[train] batch 400/645 - loss: 0.001506

[train] batch 600/645 - loss: 0.001499

[train] batch 645/645 - loss: 0.001501

[val] batch 1/121 - loss: 0.002233

[val] batch 121/121 - loss: 0.002218

Epoch 11/20 - train_loss: 0.001501, val_loss: 0.002218, time: 5.6s

No improvement. Early-stop patience left: 4

[train] batch 1/645 - loss: 0.001649

[train] batch 200/645 - loss: 0.001484

[train] batch 400/645 - loss: 0.001483

[train] batch 600/645 - loss: 0.001495

[train] batch 645/645 - loss: 0.001496

[val] batch 1/121 - loss: 0.002111

[val] batch 121/121 - loss: 0.002169

Epoch 12/20 - train_loss: 0.001496, val_loss: 0.002169, time: 5.1s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001278

[train] batch 200/645 - loss: 0.001486

[train] batch 400/645 - loss: 0.001487

[train] batch 600/645 - loss: 0.001501

[train] batch 645/645 - loss: 0.001488

[val] batch 1/121 - loss: 0.001976

[val] batch 121/121 - loss: 0.002167

Epoch 13/20 - train_loss: 0.001488, val_loss: 0.002167, time: 5.3s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001166

[train] batch 200/645 - loss: 0.001479

[train] batch 400/645 - loss: 0.001481

[train] batch 600/645 - loss: 0.001489

[train] batch 645/645 - loss: 0.001491

[val] batch 1/121 - loss: 0.002055

[val] batch 121/121 - loss: 0.002168

Epoch 14/20 - train_loss: 0.001491, val_loss: 0.002168, time: 5.5s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.002045

[train] batch 200/645 - loss: 0.001524

[train] batch 400/645 - loss: 0.001490

[train] batch 600/645 - loss: 0.001492

[train] batch 645/645 - loss: 0.001492

[val] batch 1/121 - loss: 0.002139

[val] batch 121/121 - loss: 0.002183

Epoch 15/20 - train_loss: 0.001492, val_loss: 0.002183, time: 5.3s

No improvement. Early-stop patience left: 4

[train] batch 1/645 - loss: 0.002540

[train] batch 200/645 - loss: 0.001433

[train] batch 400/645 - loss: 0.001493

[train] batch 600/645 - loss: 0.001493

[train] batch 645/645 - loss: 0.001487

[val] batch 1/121 - loss: 0.002078

[val] batch 121/121 - loss: 0.002194

Epoch 16/20 - train_loss: 0.001487, val_loss: 0.002194, time: 5.8s

No improvement. Early-stop patience left: 3

[train] batch 1/645 - loss: 0.001472

[train] batch 200/645 - loss: 0.001494

[train] batch 400/645 - loss: 0.001488

[train] batch 600/645 - loss: 0.001485

[train] batch 645/645 - loss: 0.001489

[val] batch 1/121 - loss: 0.001980

[val] batch 121/121 - loss: 0.002162

Epoch 17/20 - train_loss: 0.001489, val_loss: 0.002162, time: 5.2s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.002020

[train] batch 200/645 - loss: 0.001470

[train] batch 400/645 - loss: 0.001486

[train] batch 600/645 - loss: 0.001475

[train] batch 645/645 - loss: 0.001482

[val] batch 1/121 - loss: 0.002118

[val] batch 121/121 - loss: 0.002172

Epoch 18/20 - train_loss: 0.001482, val_loss: 0.002172, time: 5.3s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.001221

[train] batch 200/645 - loss: 0.001516

[train] batch 400/645 - loss: 0.001485

[train] batch 600/645 - loss: 0.001487

[train] batch 645/645 - loss: 0.001487

[val] batch 1/121 - loss: 0.002109

[val] batch 121/121 - loss: 0.002173

Epoch 19/20 - train_loss: 0.001487, val_loss: 0.002173, time: 5.2s

No improvement. Early-stop patience left: 4

[train] batch 1/645 - loss: 0.001512

[train] batch 200/645 - loss: 0.001479

[train] batch 400/645 - loss: 0.001488

[train] batch 600/645 - loss: 0.001481

[train] batch 645/645 - loss: 0.001484

[val] batch 1/121 - loss: 0.002022

[val] batch 121/121 - loss: 0.002172

Epoch 20/20 - train_loss: 0.001484, val_loss: 0.002172, time: 5.1s

No improvement. Early-stop patience left: 3

Warning: RNN validation MSE (0.002162) is indistinguishable from the zero-prediction baseline (0.002135); the model likely collapsed to the unconditional mean.

=== Notebook model: LSTM (seed=42) ===

=== Training LSTM ===

[train] batch 1/645 - loss: 0.167415

[train] batch 200/645 - loss: 0.004549

[train] batch 400/645 - loss: 0.003078

[train] batch 600/645 - loss: 0.002604

[train] batch 645/645 - loss: 0.002540

[val] batch 1/121 - loss: 0.002190

[val] batch 121/121 - loss: 0.002181

Epoch 1/25 - train_loss: 0.002540, val_loss: 0.002181, time: 6.2s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001061

[train] batch 200/645 - loss: 0.001525

[train] batch 400/645 - loss: 0.001569

[train] batch 600/645 - loss: 0.001545

[train] batch 645/645 - loss: 0.001556

[val] batch 1/121 - loss: 0.001995

[val] batch 121/121 - loss: 0.002143

Epoch 2/25 - train_loss: 0.001556, val_loss: 0.002143, time: 6.1s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001961

[train] batch 200/645 - loss: 0.001493

[train] batch 400/645 - loss: 0.001505

[train] batch 600/645 - loss: 0.001514

[train] batch 645/645 - loss: 0.001519

[val] batch 1/121 - loss: 0.002022

[val] batch 121/121 - loss: 0.002141

Epoch 3/25 - train_loss: 0.001519, val_loss: 0.002141, time: 6.3s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001796

[train] batch 200/645 - loss: 0.001472

[train] batch 400/645 - loss: 0.001487

[train] batch 600/645 - loss: 0.001493

[train] batch 645/645 - loss: 0.001497

[val] batch 1/121 - loss: 0.002066

[val] batch 121/121 - loss: 0.002138

Epoch 4/25 - train_loss: 0.001497, val_loss: 0.002138, time: 6.1s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001086

[train] batch 200/645 - loss: 0.001478

[train] batch 400/645 - loss: 0.001495

[train] batch 600/645 - loss: 0.001489

[train] batch 645/645 - loss: 0.001487

[val] batch 1/121 - loss: 0.002087

[val] batch 121/121 - loss: 0.002138

Epoch 5/25 - train_loss: 0.001487, val_loss: 0.002138, time: 6.2s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.001131

[train] batch 200/645 - loss: 0.001441

[train] batch 400/645 - loss: 0.001454

[train] batch 600/645 - loss: 0.001472

[train] batch 645/645 - loss: 0.001485

[val] batch 1/121 - loss: 0.002127

[val] batch 121/121 - loss: 0.002155

Epoch 6/25 - train_loss: 0.001485, val_loss: 0.002155, time: 6.6s

No improvement. Early-stop patience left: 4

[train] batch 1/645 - loss: 0.001589

[train] batch 200/645 - loss: 0.001484

[train] batch 400/645 - loss: 0.001493

[train] batch 600/645 - loss: 0.001481

[train] batch 645/645 - loss: 0.001485

[val] batch 1/121 - loss: 0.002042

[val] batch 121/121 - loss: 0.002145

Epoch 7/25 - train_loss: 0.001485, val_loss: 0.002145, time: 6.0s

No improvement. Early-stop patience left: 3

[train] batch 1/645 - loss: 0.001225

[train] batch 200/645 - loss: 0.001504

[train] batch 400/645 - loss: 0.001494

[train] batch 600/645 - loss: 0.001485

[train] batch 645/645 - loss: 0.001484

[val] batch 1/121 - loss: 0.002121

[val] batch 121/121 - loss: 0.002150

Epoch 8/25 - train_loss: 0.001484, val_loss: 0.002150, time: 6.0s

No improvement. Early-stop patience left: 2

[train] batch 1/645 - loss: 0.000950

[train] batch 200/645 - loss: 0.001473

[train] batch 400/645 - loss: 0.001501

[train] batch 600/645 - loss: 0.001491

[train] batch 645/645 - loss: 0.001485

[val] batch 1/121 - loss: 0.002047

[val] batch 121/121 - loss: 0.002141

Epoch 9/25 - train_loss: 0.001485, val_loss: 0.002141, time: 6.0s

No improvement. Early-stop patience left: 1

[train] batch 1/645 - loss: 0.000946

[train] batch 200/645 - loss: 0.001494

[train] batch 400/645 - loss: 0.001485

[train] batch 600/645 - loss: 0.001481

[train] batch 645/645 - loss: 0.001484

[val] batch 1/121 - loss: 0.002053

[val] batch 121/121 - loss: 0.002139

Epoch 10/25 - train_loss: 0.001484, val_loss: 0.002139, time: 6.2s

No improvement. Early-stop patience left: 0

Early stopping triggered.

Warning: LSTM validation MSE (0.002138) is indistinguishable from the zero-prediction baseline (0.002135); the model likely collapsed to the unconditional mean.

=== Notebook model: GRU (seed=42) ===

=== Training GRU ===

[train] batch 1/645 - loss: 0.019666

[train] batch 200/645 - loss: 0.004800

[train] batch 400/645 - loss: 0.003300

[train] batch 600/645 - loss: 0.002766

[train] batch 645/645 - loss: 0.002692

[val] batch 1/121 - loss: 0.002112

[val] batch 121/121 - loss: 0.002147

Epoch 1/25 - train_loss: 0.002692, val_loss: 0.002147, time: 6.1s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001468

[train] batch 200/645 - loss: 0.001603

[train] batch 400/645 - loss: 0.001585

[train] batch 600/645 - loss: 0.001570

[train] batch 645/645 - loss: 0.001570

[val] batch 1/121 - loss: 0.002078

[val] batch 121/121 - loss: 0.002148

Epoch 2/25 - train_loss: 0.001570, val_loss: 0.002148, time: 5.9s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.001255

[train] batch 200/645 - loss: 0.001548

[train] batch 400/645 - loss: 0.001529

[train] batch 600/645 - loss: 0.001528

[train] batch 645/645 - loss: 0.001528

[val] batch 1/121 - loss: 0.002078

[val] batch 121/121 - loss: 0.002153

Epoch 3/25 - train_loss: 0.001528, val_loss: 0.002153, time: 6.0s

No improvement. Early-stop patience left: 4

[train] batch 1/645 - loss: 0.001908

[train] batch 200/645 - loss: 0.001474

[train] batch 400/645 - loss: 0.001493

[train] batch 600/645 - loss: 0.001510

[train] batch 645/645 - loss: 0.001512

[val] batch 1/121 - loss: 0.002170

[val] batch 121/121 - loss: 0.002172

Epoch 4/25 - train_loss: 0.001512, val_loss: 0.002172, time: 7.9s

No improvement. Early-stop patience left: 3

[train] batch 1/645 - loss: 0.000948

[train] batch 200/645 - loss: 0.001531

[train] batch 400/645 - loss: 0.001487

[train] batch 600/645 - loss: 0.001493

[train] batch 645/645 - loss: 0.001500

[val] batch 1/121 - loss: 0.002104

[val] batch 121/121 - loss: 0.002160

Epoch 5/25 - train_loss: 0.001500, val_loss: 0.002160, time: 7.3s

No improvement. Early-stop patience left: 2

[train] batch 1/645 - loss: 0.001457

[train] batch 200/645 - loss: 0.001570

[train] batch 400/645 - loss: 0.001510

[train] batch 600/645 - loss: 0.001490

[train] batch 645/645 - loss: 0.001491

[val] batch 1/121 - loss: 0.002070

[val] batch 121/121 - loss: 0.002151

Epoch 6/25 - train_loss: 0.001491, val_loss: 0.002151, time: 5.9s

No improvement. Early-stop patience left: 1

[train] batch 1/645 - loss: 0.001492

[train] batch 200/645 - loss: 0.001517

[train] batch 400/645 - loss: 0.001486

[train] batch 600/645 - loss: 0.001495

[train] batch 645/645 - loss: 0.001489

[val] batch 1/121 - loss: 0.002023

[val] batch 121/121 - loss: 0.002139

Epoch 7/25 - train_loss: 0.001489, val_loss: 0.002139, time: 5.9s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.001174

[train] batch 200/645 - loss: 0.001490

[train] batch 400/645 - loss: 0.001466

[train] batch 600/645 - loss: 0.001474

[train] batch 645/645 - loss: 0.001486

[val] batch 1/121 - loss: 0.002077

[val] batch 121/121 - loss: 0.002141

Epoch 8/25 - train_loss: 0.001486, val_loss: 0.002141, time: 6.1s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.000981

[train] batch 200/645 - loss: 0.001459

[train] batch 400/645 - loss: 0.001490

[train] batch 600/645 - loss: 0.001481

[train] batch 645/645 - loss: 0.001482

[val] batch 1/121 - loss: 0.002078

[val] batch 121/121 - loss: 0.002143

Epoch 9/25 - train_loss: 0.001482, val_loss: 0.002143, time: 5.9s

No improvement. Early-stop patience left: 4

[train] batch 1/645 - loss: 0.001461

[train] batch 200/645 - loss: 0.001422

[train] batch 400/645 - loss: 0.001460

[train] batch 600/645 - loss: 0.001477

[train] batch 645/645 - loss: 0.001480

[val] batch 1/121 - loss: 0.002034

[val] batch 121/121 - loss: 0.002138

Epoch 10/25 - train_loss: 0.001480, val_loss: 0.002138, time: 5.9s

Validation improved; checkpoint updated.

[train] batch 1/645 - loss: 0.000917

[train] batch 200/645 - loss: 0.001474

[train] batch 400/645 - loss: 0.001482

[train] batch 600/645 - loss: 0.001485

[train] batch 645/645 - loss: 0.001480

[val] batch 1/121 - loss: 0.002033

[val] batch 121/121 - loss: 0.002140

Epoch 11/25 - train_loss: 0.001480, val_loss: 0.002140, time: 6.2s

No improvement. Early-stop patience left: 5

[train] batch 1/645 - loss: 0.001225

[train] batch 200/645 - loss: 0.001476

[train] batch 400/645 - loss: 0.001474

[train] batch 600/645 - loss: 0.001485

[train] batch 645/645 - loss: 0.001477

[val] batch 1/121 - loss: 0.002109

[val] batch 121/121 - loss: 0.002149

Epoch 12/25 - train_loss: 0.001477, val_loss: 0.002149, time: 5.9s

No improvement. Early-stop patience left: 4

[train] batch 1/645 - loss: 0.001683

[train] batch 200/645 - loss: 0.001439

[train] batch 400/645 - loss: 0.001452

[train] batch 600/645 - loss: 0.001472

[train] batch 645/645 - loss: 0.001477

[val] batch 1/121 - loss: 0.002082

[val] batch 121/121 - loss: 0.002146

Epoch 13/25 - train_loss: 0.001477, val_loss: 0.002146, time: 6.1s

No improvement. Early-stop patience left: 3

[train] batch 1/645 - loss: 0.001641

[train] batch 200/645 - loss: 0.001431

[train] batch 400/645 - loss: 0.001479

[train] batch 600/645 - loss: 0.001478

[train] batch 645/645 - loss: 0.001476

[val] batch 1/121 - loss: 0.002104

[val] batch 121/121 - loss: 0.002149

Epoch 14/25 - train_loss: 0.001476, val_loss: 0.002149, time: 6.6s

No improvement. Early-stop patience left: 2

[train] batch 1/645 - loss: 0.001943

[train] batch 200/645 - loss: 0.001479

[train] batch 400/645 - loss: 0.001470

[train] batch 600/645 - loss: 0.001474

[train] batch 645/645 - loss: 0.001476

[val] batch 1/121 - loss: 0.002119

[val] batch 121/121 - loss: 0.002154

Epoch 15/25 - train_loss: 0.001476, val_loss: 0.002154, time: 6.5s

No improvement. Early-stop patience left: 1

[train] batch 1/645 - loss: 0.001901

[train] batch 200/645 - loss: 0.001461

[train] batch 400/645 - loss: 0.001466

[train] batch 600/645 - loss: 0.001480

[train] batch 645/645 - loss: 0.001475

[val] batch 1/121 - loss: 0.002098

[val] batch 121/121 - loss: 0.002148

Epoch 16/25 - train_loss: 0.001475, val_loss: 0.002148, time: 6.1s

No improvement. Early-stop patience left: 0

Early stopping triggered.

Warning: GRU validation MSE (0.002138) is indistinguishable from the zero-prediction baseline (0.002135); the model likely collapsed to the unconditional mean.

=== Notebook model: TRANSFORMER (seed=42) ===

=== Training TRANSFORMER ===

[train] batch 1/323 - loss: 0.026453

[train] batch 200/323 - loss: 0.009584

[train] batch 323/323 - loss: 0.007664

[val] batch 1/61 - loss: 0.002238

[val] batch 61/61 - loss: 0.002386

Epoch 1/35 - train_loss: 0.007664, val_loss: 0.002386, time: 18.7s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.003786

[train] batch 200/323 - loss: 0.003388

[train] batch 323/323 - loss: 0.003185

[val] batch 1/61 - loss: 0.002065

[val] batch 61/61 - loss: 0.002257

Epoch 2/35 - train_loss: 0.003185, val_loss: 0.002257, time: 18.9s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.003324

[train] batch 200/323 - loss: 0.002639

[train] batch 323/323 - loss: 0.002567

[val] batch 1/61 - loss: 0.002020

[val] batch 61/61 - loss: 0.002233

Epoch 3/35 - train_loss: 0.002567, val_loss: 0.002233, time: 19.1s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.002236

[train] batch 200/323 - loss: 0.002394

[train] batch 323/323 - loss: 0.002337

[val] batch 1/61 - loss: 0.001968

[val] batch 61/61 - loss: 0.002235

Epoch 4/35 - train_loss: 0.002337, val_loss: 0.002235, time: 18.9s

No improvement. Early-stop patience left: 9

[train] batch 1/323 - loss: 0.002565

[train] batch 200/323 - loss: 0.002244

[train] batch 323/323 - loss: 0.002226

[val] batch 1/61 - loss: 0.001985

[val] batch 61/61 - loss: 0.002220

Epoch 5/35 - train_loss: 0.002226, val_loss: 0.002220, time: 18.7s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.002148

[train] batch 200/323 - loss: 0.002128

[train] batch 323/323 - loss: 0.002090

[val] batch 1/61 - loss: 0.001932

[val] batch 61/61 - loss: 0.002186

Epoch 6/35 - train_loss: 0.002090, val_loss: 0.002186, time: 18.8s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.002561

[train] batch 200/323 - loss: 0.002009

[train] batch 323/323 - loss: 0.002003

[val] batch 1/61 - loss: 0.001926

[val] batch 61/61 - loss: 0.002175

Epoch 7/35 - train_loss: 0.002003, val_loss: 0.002175, time: 19.0s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.001543

[train] batch 200/323 - loss: 0.001933

[train] batch 323/323 - loss: 0.001929

[val] batch 1/61 - loss: 0.001920

[val] batch 61/61 - loss: 0.002162

Epoch 8/35 - train_loss: 0.001929, val_loss: 0.002162, time: 19.0s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.003427

[train] batch 200/323 - loss: 0.001874

[train] batch 323/323 - loss: 0.001883

[val] batch 1/61 - loss: 0.001920

[val] batch 61/61 - loss: 0.002167

Epoch 9/35 - train_loss: 0.001883, val_loss: 0.002167, time: 18.8s

No improvement. Early-stop patience left: 9

[train] batch 1/323 - loss: 0.001649

[train] batch 200/323 - loss: 0.001847

[train] batch 323/323 - loss: 0.001821

[val] batch 1/61 - loss: 0.002005

[val] batch 61/61 - loss: 0.002223

Epoch 10/35 - train_loss: 0.001821, val_loss: 0.002223, time: 18.8s

No improvement. Early-stop patience left: 8

[train] batch 1/323 - loss: 0.001598

[train] batch 200/323 - loss: 0.001769

[train] batch 323/323 - loss: 0.001781

[val] batch 1/61 - loss: 0.001961

[val] batch 61/61 - loss: 0.002187

Epoch 11/35 - train_loss: 0.001781, val_loss: 0.002187, time: 18.8s

No improvement. Early-stop patience left: 7

[train] batch 1/323 - loss: 0.001830

[train] batch 200/323 - loss: 0.001771

[train] batch 323/323 - loss: 0.001758

[val] batch 1/61 - loss: 0.001973

[val] batch 61/61 - loss: 0.002198

Epoch 12/35 - train_loss: 0.001758, val_loss: 0.002198, time: 18.9s

No improvement. Early-stop patience left: 6

[train] batch 1/323 - loss: 0.001924

[train] batch 200/323 - loss: 0.001762

[train] batch 323/323 - loss: 0.001733

[val] batch 1/61 - loss: 0.001914

[val] batch 61/61 - loss: 0.002160

Epoch 13/35 - train_loss: 0.001733, val_loss: 0.002160, time: 18.9s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.001626

[train] batch 200/323 - loss: 0.001694

[train] batch 323/323 - loss: 0.001697

[val] batch 1/61 - loss: 0.001932

[val] batch 61/61 - loss: 0.002170

Epoch 14/35 - train_loss: 0.001697, val_loss: 0.002170, time: 18.8s

No improvement. Early-stop patience left: 9

[train] batch 1/323 - loss: 0.001611

[train] batch 200/323 - loss: 0.001670

[train] batch 323/323 - loss: 0.001686

[val] batch 1/61 - loss: 0.001910

[val] batch 61/61 - loss: 0.002157

Epoch 15/35 - train_loss: 0.001686, val_loss: 0.002157, time: 18.9s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.001272

[train] batch 200/323 - loss: 0.001649

[train] batch 323/323 - loss: 0.001667

[val] batch 1/61 - loss: 0.001994

[val] batch 61/61 - loss: 0.002216

Epoch 16/35 - train_loss: 0.001667, val_loss: 0.002216, time: 18.8s

No improvement. Early-stop patience left: 9

[train] batch 1/323 - loss: 0.001782

[train] batch 200/323 - loss: 0.001657

[train] batch 323/323 - loss: 0.001658

[val] batch 1/61 - loss: 0.001910

[val] batch 61/61 - loss: 0.002155

Epoch 17/35 - train_loss: 0.001658, val_loss: 0.002155, time: 18.8s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.001721

[train] batch 200/323 - loss: 0.001639

[train] batch 323/323 - loss: 0.001640

[val] batch 1/61 - loss: 0.001902

[val] batch 61/61 - loss: 0.002152

Epoch 18/35 - train_loss: 0.001640, val_loss: 0.002152, time: 18.8s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.001629

[train] batch 200/323 - loss: 0.001644

[train] batch 323/323 - loss: 0.001629

[val] batch 1/61 - loss: 0.001935

[val] batch 61/61 - loss: 0.002170

Epoch 19/35 - train_loss: 0.001629, val_loss: 0.002170, time: 19.0s

No improvement. Early-stop patience left: 9

[train] batch 1/323 - loss: 0.001397

[train] batch 200/323 - loss: 0.001631

[train] batch 323/323 - loss: 0.001623

[val] batch 1/61 - loss: 0.001896

[val] batch 61/61 - loss: 0.002147

Epoch 20/35 - train_loss: 0.001623, val_loss: 0.002147, time: 18.8s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.001395

[train] batch 200/323 - loss: 0.001633

[train] batch 323/323 - loss: 0.001615

[val] batch 1/61 - loss: 0.001898

[val] batch 61/61 - loss: 0.002149

Epoch 21/35 - train_loss: 0.001615, val_loss: 0.002149, time: 18.8s

No improvement. Early-stop patience left: 9

[train] batch 1/323 - loss: 0.001320

[train] batch 200/323 - loss: 0.001622

[train] batch 323/323 - loss: 0.001598

[val] batch 1/61 - loss: 0.001906

[val] batch 61/61 - loss: 0.002151

Epoch 22/35 - train_loss: 0.001598, val_loss: 0.002151, time: 18.9s

No improvement. Early-stop patience left: 8

[train] batch 1/323 - loss: 0.001949

[train] batch 200/323 - loss: 0.001591

[train] batch 323/323 - loss: 0.001600

[val] batch 1/61 - loss: 0.001963

[val] batch 61/61 - loss: 0.002191

Epoch 23/35 - train_loss: 0.001600, val_loss: 0.002191, time: 18.8s

No improvement. Early-stop patience left: 7

[train] batch 1/323 - loss: 0.001711

[train] batch 200/323 - loss: 0.001571

[train] batch 323/323 - loss: 0.001593

[val] batch 1/61 - loss: 0.001940

[val] batch 61/61 - loss: 0.002170

Epoch 24/35 - train_loss: 0.001593, val_loss: 0.002170, time: 18.9s

No improvement. Early-stop patience left: 6

[train] batch 1/323 - loss: 0.002038

[train] batch 200/323 - loss: 0.001596

[train] batch 323/323 - loss: 0.001590

[val] batch 1/61 - loss: 0.001969

[val] batch 61/61 - loss: 0.002194

Epoch 25/35 - train_loss: 0.001590, val_loss: 0.002194, time: 18.9s

No improvement. Early-stop patience left: 5

[train] batch 1/323 - loss: 0.001611

[train] batch 200/323 - loss: 0.001601

[train] batch 323/323 - loss: 0.001584

[val] batch 1/61 - loss: 0.001963

[val] batch 61/61 - loss: 0.002182

Epoch 26/35 - train_loss: 0.001584, val_loss: 0.002182, time: 18.9s

No improvement. Early-stop patience left: 4

[train] batch 1/323 - loss: 0.001320

[train] batch 200/323 - loss: 0.001575

[train] batch 323/323 - loss: 0.001575

[val] batch 1/61 - loss: 0.001903

[val] batch 61/61 - loss: 0.002147

Epoch 27/35 - train_loss: 0.001575, val_loss: 0.002147, time: 18.9s

Validation improved; checkpoint updated.

[train] batch 1/323 - loss: 0.001665

[train] batch 200/323 - loss: 0.001567

[train] batch 323/323 - loss: 0.001576

[val] batch 1/61 - loss: 0.001978

[val] batch 61/61 - loss: 0.002197

Epoch 28/35 - train_loss: 0.001576, val_loss: 0.002197, time: 19.0s

No improvement. Early-stop patience left: 9

[train] batch 1/323 - loss: 0.001832

[train] batch 200/323 - loss: 0.001577

[train] batch 323/323 - loss: 0.001570

[val] batch 1/61 - loss: 0.001921

[val] batch 61/61 - loss: 0.002164

Epoch 29/35 - train_loss: 0.001570, val_loss: 0.002164, time: 18.9s

No improvement. Early-stop patience left: 8

[train] batch 1/323 - loss: 0.001578

[train] batch 200/323 - loss: 0.001558

[train] batch 323/323 - loss: 0.001572

[val] batch 1/61 - loss: 0.001922

[val] batch 61/61 - loss: 0.002163

Epoch 30/35 - train_loss: 0.001572, val_loss: 0.002163, time: 18.9s

No improvement. Early-stop patience left: 7

[train] batch 1/323 - loss: 0.001294

[train] batch 200/323 - loss: 0.001524

[train] batch 323/323 - loss: 0.001561

[val] batch 1/61 - loss: 0.001906

[val] batch 61/61 - loss: 0.002152

Epoch 31/35 - train_loss: 0.001561, val_loss: 0.002152, time: 18.9s

No improvement. Early-stop patience left: 6

[train] batch 1/323 - loss: 0.001642

[train] batch 200/323 - loss: 0.001560

[train] batch 323/323 - loss: 0.001561

[val] batch 1/61 - loss: 0.001915

[val] batch 61/61 - loss: 0.002154

Epoch 32/35 - train_loss: 0.001561, val_loss: 0.002154, time: 18.9s

No improvement. Early-stop patience left: 5

[train] batch 1/323 - loss: 0.001331

[train] batch 200/323 - loss: 0.001558

[train] batch 323/323 - loss: 0.001560

[val] batch 1/61 - loss: 0.001911

[val] batch 61/61 - loss: 0.002152

Epoch 33/35 - train_loss: 0.001560, val_loss: 0.002152, time: 18.9s

No improvement. Early-stop patience left: 4

[train] batch 1/323 - loss: 0.001615

[train] batch 200/323 - loss: 0.001556

[train] batch 323/323 - loss: 0.001560

[val] batch 1/61 - loss: 0.001907

[val] batch 61/61 - loss: 0.002150

Epoch 34/35 - train_loss: 0.001560, val_loss: 0.002150, time: 18.9s

No improvement. Early-stop patience left: 3

[train] batch 1/323 - loss: 0.001324

[train] batch 200/323 - loss: 0.001566

[train] batch 323/323 - loss: 0.001554

[val] batch 1/61 - loss: 0.001913

[val] batch 61/61 - loss: 0.002154

Epoch 35/35 - train_loss: 0.001554, val_loss: 0.002154, time: 18.8s

No improvement. Early-stop patience left: 2

Warning: TRANSFORMER validation MSE (0.002147) is indistinguishable from the zero-prediction baseline (0.002135); the model likely collapsed to the unconditional mean.

In [5]:
summary = srp.build_summary_frame(results)
summary

,model,mean_ic,std_ic,ic_t_stat,mean_rank_ic,std_rank_ic,rank_ic_t_stat,mean_return,volatility,sharpe_ratio
0,TRANSFORMER,0.081623,0.313623,4.611781,0.055979,0.285949,3.468983,0.007258,0.026972,4.271542
1,LSTM,0.067292,0.277998,4.289335,0.046877,0.250773,3.312428,0.006698,0.024165,4.400267
2,GRU,0.066983,0.250178,4.744425,0.052918,0.244788,3.830688,0.006469,0.023143,4.437182
3,RNN,0.018729,0.201266,1.648936,0.016397,0.185735,1.564329,0.001392,0.019289,1.145264

# Result Visualizations

Plots for loss curves, IC/RankIC, portfolio performance, and model comparison.

In [6]:
import matplotlib.pyplot as plt

best_model = summary.iloc[0]["model"]
print("Visualizing model:", best_model)
training_fig = srp.plot_training_histories(results)
display(training_fig)
plt.close(training_fig)

Visualizing model: TRANSFORMER

In [7]:
import matplotlib.pyplot as plt

ic_fig = srp.plot_ic_series(results, best_model, split="test", rolling_window=20)
display(ic_fig)
plt.close(ic_fig)

In [8]:
import matplotlib.pyplot as plt

for model_name, result in results.items():
    if "portfolio_curve" not in result:
        portfolio_curve, portfolio_summary = srp.backtest_long_short(result["test_predictions"])
        result["portfolio_curve"] = portfolio_curve
        result["portfolio_summary"] = portfolio_summary

portfolio_fig = srp.plot_portfolio_curve(results, best_model)
summary_fig = srp.plot_summary_bars(summary)
display(portfolio_fig)
display(summary_fig)
plt.close(portfolio_fig)
plt.close(summary_fig)

# Prediction diagnostics

Inspect raw predictions, sign accuracy, and the prediction-vs-target scatter plot.

In [9]:
model_name = best_model
pred = results[model_name]["test_predictions"].copy()
pred.head()

        Date Ticker  prediction    target
0 2023-09-26   AAPL    0.006715  0.002559
1 2023-09-26   ABBV    0.004678 -0.042103
2 2023-09-26    ABT    0.004233 -0.004572
3 2023-09-26   ADBE    0.005884  0.001442
4 2023-09-26    AMD    0.011096  0.042935

In [10]:
pred["pred_sign"] = (pred["prediction"] > 0).astype(int)
pred["true_sign"] = (pred["target"] > 0).astype(int)

sign_accuracy = (pred["pred_sign"] == pred["true_sign"]).mean()
daily_sign_accuracy = pred.groupby("Date").apply(
    lambda x: ((x["prediction"] > 0) == (x["target"] > 0)).mean(),
    include_groups=False,
)

print("Overall sign accuracy:", round(float(sign_accuracy), 4))
daily_sign_accuracy.describe()

Overall sign accuracy: 0.5656

count    314.000000
mean       0.565579
std        0.207496
min        0.081633
25%        0.428571
50%        0.571429
75%        0.734694
max        1.000000
dtype: float64

In [11]:
import matplotlib.pyplot as plt

latest_day = pred["Date"].max()
latest_slice = pred[pred["Date"] == latest_day].copy()
display(latest_slice.sort_values("prediction", ascending=False).head(10))

ax = latest_slice.plot.scatter(
    x="prediction",
    y="target",
    figsize=(6, 5),
    alpha=0.7,
    title=f"{model_name} prediction vs target on {latest_day.date()}"
)
ax.axhline(0.0, color="black", linewidth=1, alpha=0.6)
ax.axvline(0.0, color="black", linewidth=1, alpha=0.6)
plt.show()

            Date Ticker  prediction    target  pred_sign  true_sign
15372 2024-12-23   NVDA    0.009607 -0.038519          1          0
15341 2024-12-23    AMD    0.008912 -0.030578          1          0
15340 2024-12-23   ADBE    0.008847 -0.004611          1          0
15381 2024-12-23    UNH    0.008291 -0.000948          1          0
15367 2024-12-23   META    0.007984 -0.023906          1          0
15343 2024-12-23   AMZN    0.007958 -0.025193          1          0
15371 2024-12-23    NOW    0.007916 -0.025858          1          0
15356 2024-12-23  GOOGL    0.007643 -0.027385          1          0
15370 2024-12-23   NFLX    0.007624 -0.022086          1          0
15344 2024-12-23   AVGO    0.007593 -0.002195          1          0